=== Byzok1/Equilibrum/worlds/world.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT world (tile*, reciepe*)>

<!ELEMENT reciepe (ressource*, unit)>

<!ELEMENT tile (terrain, position)>

<!ELEMENT terrain (terrainEntity, terrainType)>

<!ELEMENT terrainEntity (#PCDATA)>
<!ELEMENT terrainType (#PCDATA)>

<!ELEMENT unit (position, team, unitType)>
<!ELEMENT unitType (#PCDATA)>

<!ELEMENT team (player+, color?, alignment)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT alignment (#PCDATA)>

<!ELEMENT player (team)>

<!ELEMENT position (X, Y)>

<!ELEMENT X (#PCDATA)>
<!ELEMENT Y (#PCDATA)>

=== Byzok1/Equilibrum/EquilibrumFX/worlds/firstWorld.xml
<?xml version="1.0" encoding="UTF-8"? standalone="no" ?>

<!DOCTYPE world SYSTEM "world.dtd">
<world>
	<tile>
		<terrain>
			<terrainEntity>blank</terrainEntity>
			<terrainType>land</terrainType>
		</terrain>
		<position>
			<X>0</X>
			<Y>0</Y>
		</position>
	</tile>
</world>
